### ISSUE TITLE
Propose CI service for running mutation testing

### ISSUE THREAD

**Issue by oscarlvp** [STAMP-project/pitest-descartes#14]
Create an infrastructure for an extreme mutation service using Github hooks.
- [ ] create a Jenkins job that fails in the presence of pseudo-tested methods.
- [ ] work only on the methods that have been changed.

**Comment by bbaudry** [comment]
We should have a webhook (https://developer.github.com/webhooks/) that triggers Descartes on a pull request.

**Comment by dvojtise** [comment]
Trigger ok, but on which execution server ?  something like calling travis/jenkins execution and then report back the result on the corresponding PR ?. (because I believe that Descartes need some computing resources...)

Actually triggering is not really an issue if you have a Jenkins/travis server,  the real point is to be able to get back the results and associate it to the correct PR in github. (if you use travis, you already have a build status report)

Don't know if that might help but in eclipse organization they have something that is run on pull request in order to check if all commits has the correct "signedOfBy" information and that the indicated user has signed his ECA document, this is reported on the PR before being merged. 
We may try to find the code for that and mimic it ?

**Comment by monperrus** [comment]
> Actually triggering is not really an issue if you have a 
> Jenkins/travis server
I agree, and this what we have
> the real point is to be able to get back the results and associate it 
> to the correct PR in github. (if you use travis, you already have a 
> build status report)
Travis is an option. Or pushing from Travis to github directly is 
another option.

**Comment by oscarlvp** [comment]
Check the alternative implemented in the INRIA/spoon.

**Comment by nicolabertazzo** [comment]
My proposal is to split this task in 3 sub tasks:

- Define a jenkins freestyle job o pipeline job that execute pitest-descartes
- Develop a jenkins plugin that from pitest-descartes output display a report in jenkins
- Develop a github hooks to run pitest-descartes for each pull request

**Comment by bbaudry** [comment]
I close the issue. I split into 3 different ones #60 #59 #58
