### ISSUE TITLE
PIT >> WARNING : Minion exited abnormally due to TIMED_OUT

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#80]
#### Characteristics
- **Issue Type**: test report
- **Reproducibility**: always
- **Severity**:  minor
- **Tool/Service/Component**: Descartes 1.2.4
- **Execution Environment**: Linux CentOS 7
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>
#### Description
When running Descartes I am getting multiple warnings like this:
`10:27:31 AM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
`
Finally, Descartes completes its execution normally and reports the issues, but I wonder if these warnings may have a negative effect on Descartes execution and how to increase the TIME_OUT to avoid them.

#### [Help on issue template](https://github.com/STAMP-project/pitest-descartes/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

When running PIT, you can play with some options to custom the time out:
1. timeoutFactor: A factor to apply to the normal runtime of a test when considering if it is stuck in an infinite loop. (Defaults to 1.25)
2. timeoutConstant  Constant amount of additional time to allow a test to run for (after the application of the timeoutFactor) before considering it to be stuck in an infinite loop. (Defaults to 3000)

You can find more information in the documentation of [PIT](http://pitest.org/quickstart/maven/).

From my experience of PIT, I always have this kind of errors. The mutation of the source code can create a invalid state for the program and for instance create an infinite loop. This is why, there is this time out mechanism.

I think this kind of errors are not a big deal, unless you have too much of it because your test suite take a while to be executed. 

Last but not least, you must be careful because between different mutation analysis this number of errors (and others like memory errors) can vary and thus bias the result if you want to observe an improvement. 
I say that because we aim at increasing the mutation score with DSpot, and you must align amplified result with your baseline in the number of errors.
